# Generated by Django 5.2.3 on 2025-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Contador', 'Contador'), ('Umidade', 'Umidade'), ('Luminosidade', 'Luminosidade')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_medida',
            field=models.CharField(choices=[('°C', 'Celsius'), ('%', 'Contador'), ('uni', 'Umidade'), ('lux', 'Luminosidade')], max_length=5),
        ),
    ]
