# Generated by Django 5.2.3 on 2025-06-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_historico_timestamp_alter_sensores_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('contador', 'Contador'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade')], max_length=30),
        ),
    ]
