# Generated by Django 5.2.3 on 2025-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sensores_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='sig',
            field=models.IntegerField(unique=True),
        ),
    ]
